@startuml DS2_RegistrarVehiculo
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

title UC 2 — Registrar Vehículo

actor Usuario

participant "ctrl : VehiculoController" as VC
participant "vehiculos : List<Vehiculo>" as LV
participant "vehiculo : Vehiculo" as V
participant "ctrlHist : HistorialController" as HC
participant "historiales : List<HistorialCambioEstado>" as LH
participant "historial : HistorialCambioEstado" as H

Usuario -> VC : registrarVehiculo(patente, marca, mod, anio, km, val, tipo, comb, kmD, cKm, usuario)
activate VC

VC -> VC : buscarVehiculoPorPatente(patente)
activate VC
VC --> VC : null
deactivate VC

VC -> V ** : new Vehiculo(patente, marca, mod, anio, km, val, tipo, comb, kmD, cKm)
VC -> V : cambiarEstado(DISPONIBLE)
activate V
deactivate V

VC -> LV : add(vehiculo)
activate LV
deactivate LV

VC -> HC : registrar("-", "DISPONIBLE", VEHICULO, patente, usuario)
activate HC

HC -> H ** : new HistorialCambioEstado(fecha, "-", "DISPONIBLE", VEHICULO, patente, usuario)
HC -> LH : add(historial)
activate LH
deactivate LH

HC --> VC : historial
deactivate HC

VC --> Usuario : vehiculo registrado
deactivate VC

@enduml
