@startuml DS5_ConsultarVehiculosDisponibles
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

title UC 5 — Consultar Vehículos Disponibles

actor Usuario

participant "view : ConsultarDisponibilidadView" as V
participant "ctrlVeh : VehiculoController" as VC
participant "ctrlAlq : AlquilerController" as AC
participant "vehiculos : List<Vehiculo>" as LV
participant "vehiculo : Vehiculo" as Veh
participant "resultado : List<Vehiculo>" as LR

Usuario -> V : consultar()
activate V

V -> VC : consultarVehiculosDisponibles(fInicio, fFin, tipo)
activate VC

VC -> AC : getAlquileres()
activate AC
AC --> VC : alquileres
deactivate AC

VC -> LR ** : new ArrayList<Vehiculo>()

loop por cada vehiculo en vehiculos
    VC -> Veh : getTipoVehiculo()
    activate Veh
    Veh --> VC : tipoVehiculoActual
    deactivate Veh

    opt tipoVehiculoActual == tipo
        VC -> Veh : estaDisponible(fInicio, fFin, alquileres)
        activate Veh
        Veh --> VC : disponible (boolean)
        deactivate Veh

        opt disponible
            VC -> LR : add(vehiculo)
            activate LR
            deactivate LR
        end
    end
end

VC --> V : resultado
deactivate VC

V --> Usuario : mostrar vehiculos disponibles
deactivate V

@enduml
