@startuml DS1_RegistrarCliente
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

title UC 1 — Registrar Cliente

actor Usuario

participant "view : RegistrarClienteView" as V
participant "ctrl : ClienteController" as CC
participant "clientes : List<Cliente>" as LC
participant "cliente : Cliente" as C
participant "ctrlHist : HistorialController" as HC
participant "historiales : List<HistorialCambioEstado>" as LH
participant "historial : HistorialCambioEstado" as H

Usuario -> V : registrarCliente()
activate V

V -> CC : registrarCliente(dniCuit, nombre, telefono, email, direccion, usuario)
activate CC

CC -> CC : buscarClientePorDniCuit(dniCuit)
activate CC
CC --> CC : null
deactivate CC

CC -> C ** : new Cliente(dniCuit, nombre, telefono, email, direccion)
CC -> C : activar()
activate C
deactivate C

CC -> LC : add(cliente)
activate LC
deactivate LC

CC -> HC : registrar("-", "ACTIVO", CLIENTE, dniCuit, usuario)
activate HC

HC -> H ** : new HistorialCambioEstado(fecha, "-", "ACTIVO", CLIENTE, dniCuit, usuario)
HC -> LH : add(historial)
activate LH
deactivate LH

HC --> CC : historial
deactivate HC

CC --> V : cliente
deactivate CC

V --> Usuario : cliente registrado
deactivate V

@enduml
