@startuml DS3_SolicitarAlquiler
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

title UC 3 — Solicitar Alquiler

actor Usuario

participant "view : SolicitarAlquilerView" as V
participant "ctrlAlq : AlquilerController" as AC
participant "ctrlCli : ClienteController" as CC
participant "ctrlVeh : VehiculoController" as VC
participant "vehiculo : Vehiculo" as Veh
participant "alquileres : List<Alquiler>" as LA
participant "alquiler : Alquiler" as A
participant "ctrlHist : HistorialController" as HC
participant "historiales : List<HistorialCambioEstado>" as LH
participant "historial : HistorialCambioEstado" as H

Usuario -> V : solicitarAlquiler()
activate V

V -> AC : solicitarAlquiler(dniCuit, patente, fInicio, fFin, clase, usuario)
activate AC

AC -> CC : buscarClientePorDniCuit(dniCuit)
activate CC
CC --> AC : cliente
deactivate CC

AC -> VC : buscarVehiculoPorPatente(patente)
activate VC
VC --> AC : vehiculo
deactivate VC

AC -> Veh : estaDisponible(fInicio, fFin, alquileres)
activate Veh
Veh --> AC : true
deactivate Veh

opt disponible
    alt clase es COMUN
        AC -> A ** : new AlquilerComun(cliente, vehiculo, fInicio, fFin, kmInicial)
    else clase es CORPORATIVO
        AC -> A ** : new AlquilerCorporativo(cliente, vehiculo, fInicio, fFin, kmInicial)
    else clase es TURISTICO
        AC -> A ** : new AlquilerTuristico(cliente, vehiculo, fInicio, fFin, kmInicial)
    end

    AC -> A : cambiarEstado(INGRESADO)
    activate A
    deactivate A

    AC -> LA : add(alquiler)
    activate LA
    deactivate LA

    AC -> A : getId()
    activate A
    A --> AC : idAlquiler
    deactivate A

    AC -> HC : registrar("-", "INGRESADO", ALQUILER, idAlquiler, usuario)
    activate HC

    HC -> H ** : new HistorialCambioEstado(fecha, "-", "INGRESADO", ALQUILER, idAlquiler, usuario)
    HC -> LH : add(historial)
    activate LH
    deactivate LH

    HC --> AC : historial
    deactivate HC
end

AC --> V : alquiler
deactivate AC

V --> Usuario : alquiler ingresado
deactivate V

@enduml
