@startuml DS4_FinalizarAlquiler
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

title UC 4 — Finalizar Alquiler y Calcular Saldo

actor Usuario

participant "ctrlAlq : AlquilerController" as AC
participant "alquiler : Alquiler" as A
participant "vehiculo : Vehiculo" as Veh
participant "ctrlHist : HistorialController" as HC
participant "historiales : List<HistorialCambioEstado>" as LH
participant "historialAlq : HistorialCambioEstado" as HA
participant "historialVeh : HistorialCambioEstado" as HV

Usuario -> AC : finalizarAlquiler(idAlquiler, kmFinal, fDevReal, usuario)
activate AC

AC -> AC : buscarPorId(idAlquiler)
activate AC
AC --> AC : alquiler
deactivate AC

AC -> A : getVehiculo()
activate A
A --> AC : vehiculo
deactivate A

AC -> Veh : actualizarKilometraje(kmFinal)
activate Veh
deactivate Veh

AC -> A : setKilometrajeFinal(kmFinal)
activate A
deactivate A

AC -> A : setFechaDevolucionReal(fDevReal)
activate A
deactivate A

AC -> A : calcularImporteTotal()
activate A
A --> AC : importeTotal
deactivate A

AC -> A : setImporteTotal(importeTotal)
activate A
deactivate A

AC -> A : calcularSaldoPendiente()
activate A
A --> AC : saldoPendiente
deactivate A

AC -> A : setImportePendiente(saldoPendiente)
activate A
deactivate A

AC -> A : cambiarEstado(FINALIZADO)
activate A
deactivate A

AC -> Veh : cambiarEstado(DISPONIBLE)
activate Veh
deactivate Veh

AC -> Veh : getPatente()
activate Veh
Veh --> AC : patente
deactivate Veh

AC -> HC : registrar("EN_CURSO", "FINALIZADO", ALQUILER, idAlquiler, usuario)
activate HC
HC -> HA ** : new HistorialCambioEstado(fecha, "EN_CURSO", "FINALIZADO", ALQUILER, idAlquiler, usuario)
HC -> LH : add(historialAlq)
activate LH
deactivate LH
HC --> AC : historialAlq
deactivate HC

AC -> HC : registrar("ALQUILADO", "DISPONIBLE", VEHICULO, patente, usuario)
activate HC
HC -> HV ** : new HistorialCambioEstado(fecha, "ALQUILADO", "DISPONIBLE", VEHICULO, patente, usuario)
HC -> LH : add(historialVeh)
activate LH
deactivate LH
HC --> AC : historialVeh
deactivate HC

AC --> Usuario : saldoPendiente
deactivate AC

@enduml